# stage-1
ARG REPO
FROM ${REPO}/gfs-intel:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

# stage-2
FROM ${REPO}/esmf-intel:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

COPY scripts/copy_deps.sh /opt

RUN mkdir -p /opt/exec
COPY --from=0 /usr/local/NCEPlibs-20190820 /usr/local/NCEPlibs-20190820
COPY --from=0 /opt/global-workflow/sorc/fv3gfs.fd/NEMS/exe/global_fv3gfs.x /opt/exec/global_fv3gfs.x
