ARG REPO
FROM ${REPO}/crtm-gempak-intel:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

COPY scripts/checkout_nceplibs.sh /opt
COPY scripts/build_nceplibs.sh /opt
COPY patches/nceplibs /opt/patches/nceplibs
