ARG REPO
FROM ${REPO}/esmf-intel:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

COPY global-workflow/sorc/fv3gfs.fd /opt/NEMSfv3gfs
COPY scripts/build_fv3.sh /opt
COPY patch_fv3.sh /opt
COPY patches/ /opt/patches
COPY scripts/copy_deps.sh /opt
