        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 19 21:38:57 2018
        MODULE SETUP_SMOOTH__genmod
          INTERFACE 
            SUBROUTINE SETUP_SMOOTH(NTRUNC,NLEVS,SMOOTHPARM,WINDOW,     &
     &SMOOTHFACT)
              INTEGER(KIND=4), INTENT(IN) :: NLEVS
              INTEGER(KIND=4), INTENT(IN) :: NTRUNC
              INTEGER(KIND=4), INTENT(IN) :: SMOOTHPARM(NLEVS)
              INTEGER(KIND=4), INTENT(IN) :: WINDOW
              REAL(KIND=8), INTENT(OUT) :: SMOOTHFACT(0:NTRUNC,0:NTRUNC,&
     &NLEVS)
            END SUBROUTINE SETUP_SMOOTH
          END INTERFACE 
        END MODULE SETUP_SMOOTH__genmod
