        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 19 21:38:57 2018
        MODULE SMOOTH__genmod
          INTERFACE 
            SUBROUTINE SMOOTH(SPECDAT,NTRUNC,SMOOTHFACT)
              INTEGER(KIND=4), INTENT(IN) :: NTRUNC
              REAL(KIND=4), INTENT(INOUT) :: SPECDAT((NTRUNC+1)*(NTRUNC+&
     &2))
              REAL(KIND=8), INTENT(IN) :: SMOOTHFACT(0:NTRUNC,0:NTRUNC)
            END SUBROUTINE SMOOTH
          END INTERFACE 
        END MODULE SMOOTH__genmod
