#!/bin/sh

#PBS -o STDDIR/test_post_RRR_CURRENTDATE.o$PBS_JOBID
#PBS -j oe
#PBS -N test_post
#PBS -l walltime=00:30:00
#PBS -l nodes=8:ppn=12
#PBS -q debug
#PBS -A ovp
#PBS -V

set -x

# specify computation resource
export threads=1
export MP_LABELIO=yes
export OMP_NUM_THREADS=$threads
export APRUN="mpirun -np $PBS_NP"

# specify user's own post working directory for testing
#export svndir=/u/Wen.Meng/noscrubc/ncep_post/post_fv3gfs_flat


############################################
# Loading module
############################################
module purge
. $MODULESHOME/init/sh
module load intel/18.1.163
module load impi/5.1.2.150
module load wgrib2
module use /scratch4/NCEPDEV/nems/noscrub/emc.nemspara/soft/modulefiles
module load prod_util
module list

#add grib utilities
export WGRIB2=/scratch3/NCEPDEV/nwprod/utils/wgrib2.v2.0.6c/wgrib2/wgrib2
export COPYGB2=/scratch4/NCEPDEV/global/save/glopara/nwpara/util/exec/copygb2
export GRBINDEX=/scratch4/NCEPDEV/global/save/glopara/nwpara/util/exec/grbindex
export GRB2INDEX=/scratch4/NCEPDEV/global/save/glopara/nwpara/util/exec/grb2index
export CNVGRIB=/apps/cnvgrib/1.4.0/bin/cnvgrib
export CNVGRIB21_GFS=/apps/cnvgrib/1.4.0/bin/cnvgrib

# specify version numbers
#export hwrf_ver=v11.0.5

# specify PDY (the cycle start yyyymmdd) and cycle
export CDATE=CURRENTDATE
export PDY=`echo $CDATE | cut -c1-8`
export cyc=`echo $CDATE | cut -c9-10`
export cycle=t${cyc}z


# specify the directory environment for executable, it's either para or prod
export envir=prod

####################################
# Specify RUN Name and model
####################################
export NET=gfs
export RUN=RRR
#export RUN=gfs

# set up running dir
export job=${RUN}_post_${cyc}
export pid=${pid:-$$}
export jobid=${job}.${pid}
mkdir -p /scratch3/NCEPDEV/stmp2/$LOGNAME/nceppost/logs
export jlogfile=/scratch3/NCEPDEV/stmp2/$LOGNAME/nceppost/logs/jlogfile.${job}.${pid}

export DATA=/scratch3/NCEPDEV/stmp2/$LOGNAME/test/$jobid
mkdir -p $DATA
cd $DATA
rm -f ${DATA}/*

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SENDCOM=YES
export SENDDBN=NO
export RERUN=NO
export VERBOSE=YES

export HOMEgfs=${svndir}

##############################################
# Define COM directories
##############################################
export COMIN=$COMINP/${RUN}.${PDY}/${cyc}
# specify my own COMOUT dir to mimic operations
export COMOUT=/scratch3/NCEPDEV/stmp2/$LOGNAME/com2/gfs/test/${RUN}.$PDY/${cyc}
mkdir -p $COMOUT

# specify variables if testing post in non gfs structure environment
#export FIXglobal=/gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/master/global_shared.v15.0.0/fix
#export FIXgfs=/gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/master/global_shared.v15.0.0/fix
export FIXgfs=/scratch4/NCEPDEV/global/save/glopara/git/fv3gfs/fix
export nemsioget=/scratch4/NCEPDEV/global/save/glopara/git/fv3gfs/master/exec/nemsio_get
#export POSTGRB2TBL=${HOMEgfs}/parm/params_grib2_tbl_new
export POSTGRB2TBL=/scratch3/NCEPDEV/nwprod/lib/g2tmpl/v1.5.0/sorc/params_grib2_tbl_new
export POSTGPEXEC=${HOMEgfs}/exec/ncep_post
export PARMpost=${HOMEgfs}/parm

#export PGBF=NO
export PGB1F=YES
export FLXF=NO
export GOESF=NO
export GTGF=NO
export KEEPDATA=NO

####################################
# Specify Forecast Hour Range
####################################

#if [ $RUN = gdas ]; then
#    #export allfhr="anl 00 03 06 09"
#    export allfhr="anl 000 006"
#elif [ $RUN = gfs ]; then
#    #export allfhr="anl 00 01 06 12 60 120 180 240 252 384"
#    export allfhr="000"
#fi

#############################################################

for post_times in $allfhr; do

    export post_times

    date

    $HOMEgfs/jobs/J_NCEPPOST

    echo $?

    date

done

#############################################################
