        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 19 21:37:24 2018
        MODULE COPY_SIGDATA__genmod
          INTERFACE 
            SUBROUTINE COPY_SIGDATA(HEAD,DATA1,DATA2)
              USE SIGIO_MODULE
              TYPE (SIGIO_HEAD), INTENT(IN) :: HEAD
              TYPE (SIGIO_DATA), INTENT(IN) :: DATA1
              TYPE (SIGIO_DATA), INTENT(INOUT) :: DATA2
            END SUBROUTINE COPY_SIGDATA
          END INTERFACE 
        END MODULE COPY_SIGDATA__genmod
