        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 19 21:37:24 2018
        MODULE INIT_SIGDATA__genmod
          INTERFACE 
            SUBROUTINE INIT_SIGDATA(HEAD,DATA)
              USE SIGIO_MODULE
              TYPE (SIGIO_HEAD), INTENT(IN) :: HEAD
              TYPE (SIGIO_DATA), INTENT(INOUT) :: DATA
            END SUBROUTINE INIT_SIGDATA
          END INTERFACE 
        END MODULE INIT_SIGDATA__genmod
