        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 19 21:37:24 2018
        MODULE SMOOTH__genmod
          INTERFACE 
            SUBROUTINE SMOOTH(SPECDAT,NTRUNC,NLEVS,SMOOTHPARM,WINDOW)
              INTEGER(KIND=4), INTENT(IN) :: NLEVS
              INTEGER(KIND=4), INTENT(IN) :: NTRUNC
              REAL(KIND=4), INTENT(INOUT) :: SPECDAT((NTRUNC+1)*(NTRUNC+&
     &2),NLEVS)
              INTEGER(KIND=4), INTENT(IN) :: SMOOTHPARM(NLEVS)
              INTEGER(KIND=4), INTENT(IN) :: WINDOW
            END SUBROUTINE SMOOTH
          END INTERFACE 
        END MODULE SMOOTH__genmod
