# stage-1
ARG REPO
FROM ${REPO}/gfs-gnu:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

# stage-2
FROM ${REPO}/esmf-gnu:latest
MAINTAINER Daniel Abdi <daniel.abdi@noaa.gov>

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libblas-dev \
        liblapack-dev \
    && rm -rf /var/lib/apt/lists/*

ARG EXECP=/opt/global-workflow/exec
RUN mkdir -p $EXECP
COPY --from=0 /opt/global-workflow/sorc/gsi.fd/exec $EXECP
