 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012010000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012020000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings048 -c 202012030000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings096 -c 202012040000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings168 -c 202012040000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012050000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings084 -c 202012060000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings060 -c 202012070000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings120 -c 202012080000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012090000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings096 -c 202012090000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings132 -c 202012090000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012100000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings156 -c 202012100000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings012 -c 202012110000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings084 -c 202012110000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings144 -c 202012110000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012130000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings084 -c 202012140000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings096 -c 202012140000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012150000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings036 -c 202012150000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings060 -c 202012150000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings096 -c 202012160000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings012 -c 202012170000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings036 -c 202012170000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012170000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012180000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012190000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings060 -c 202012190000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012190000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings108 -c 202012200000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings012 -c 202012210000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012210000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012220000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings036 -c 202012220000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings072 -c 202012220000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings132 -c 202012220000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings144 -c 202012220000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings060 -c 202012230000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings168 -c 202012230000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings120 -c 202012240000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings132 -c 202012240000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings024 -c 202012250000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings012 -c 202012260000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings096 -c 202012260000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings120 -c 202012260000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -t soundings132 -c 202012260000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db


