 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012270000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012270000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012270000 -t soundings156  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012270000 -t soundings168  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012280000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012280000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012290000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012290000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012290000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012290000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202012300000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101010000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101020000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101020000 -t soundings156  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101020000 -t soundings168  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101030000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101040000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101040000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101060000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101070000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101070000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101070000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101070000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101080000 -t soundings156  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101090000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101090000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101090000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101100000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101100000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101110000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101110000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101120000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101140000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101140000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101150000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101150000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101150000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101160000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101170000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101170000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101170000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101180000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101180000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101180000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101180000 -t soundings108  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101200000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101220000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101220000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101220000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101220000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101220000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101230000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101230000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101240000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101240000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101260000 -t soundings108  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101260000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101270000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101270000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101270000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101280000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101280000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101280000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101280000 -t soundings144  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101290000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101310000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202101310000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102010000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102020000 -t soundings108  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102020000 -t soundings144  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102040000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102040000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102050000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102050000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102050000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102050000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102060000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102060000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102060000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102060000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102070000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102070000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings108  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102080000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102090000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102090000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102090000 -t soundings144  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102100000 -t soundings036  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102110000 -t soundings072  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102120000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102120000 -t soundings144  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102130000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102130000 -t soundings060  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102150000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102160000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102160000 -t soundings096  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102180000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102190000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102190000 -t soundings084  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102190000 -t soundings120  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102190000 -t soundings132  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102200000 -t soundings000  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102200000 -t soundings048  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102220000 -t soundings012  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
 rocotorewind -w /scratch1/BMC/gsd-fv3/rtruns/CCPP-Chem/FV3GFSwfm/xml/ccppchem_retro_raobvx.xml -c 202102220000 -t soundings024  -d /home/rtfim/retro_dbfiles/ccppchem_retro_raobvx.db
